spring:
  application:
    name: api
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: "br.com.ariel.api.domain.model.conta.Conta"
            use:
              type:
                headers: false

server:
  port: 8080

